/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extras from "./Extras";
export type { extras };
import type * as polygonIdSol from "./PolygonId.sol";
export type { polygonIdSol };
