/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gnosis from "./gnosis";
export type { gnosis };
import type * as interfaces from "./interfaces";
export type { interfaces };
