/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../../../common";
import type {
  AssetLogic,
  AssetLogicInterface,
} from "../../../../../../../@connext/nxtp-contracts/contracts/core/connext/libraries/AssetLogic";

const _abi = [
  {
    inputs: [],
    name: "AssetLogic__getConfig_notRegistered",
    type: "error",
  },
  {
    inputs: [],
    name: "AssetLogic__getTokenIndexFromStableSwapPool_notExist",
    type: "error",
  },
  {
    inputs: [],
    name: "AssetLogic__handleIncomingAsset_feeOnTransferNotSupported",
    type: "error",
  },
  {
    inputs: [],
    name: "AssetLogic__handleIncomingAsset_nativeAssetNotSupported",
    type: "error",
  },
  {
    inputs: [],
    name: "AssetLogic__handleOutgoingAsset_notNative",
    type: "error",
  },
  {
    inputs: [],
    name: "AssetLogic__swapAsset_externalStableSwapPoolDoesNotExist",
    type: "error",
  },
];

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212204827ec5069eac34303e8e6edc1bd3c5a45c40a95c063854f84c8e0281187a81a64736f6c63430008110033";

type AssetLogicConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AssetLogicConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AssetLogic__factory extends ContractFactory {
  constructor(...args: AssetLogicConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AssetLogic> {
    return super.deploy(overrides || {}) as Promise<AssetLogic>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AssetLogic {
    return super.attach(address) as AssetLogic;
  }
  override connect(signer: Signer): AssetLogic__factory {
    return super.connect(signer) as AssetLogic__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssetLogicInterface {
    return new utils.Interface(_abi) as AssetLogicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AssetLogic {
    return new Contract(address, _abi, signerOrProvider) as AssetLogic;
  }
}
