/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as polygonId from "./polygon-id";
export { DigiGoWallet__factory } from "./DigiGoWallet__factory";
export { DigiGoWalletDeployer__factory } from "./DigiGoWalletDeployer__factory";
export { MockPayment__factory } from "./MockPayment__factory";
