/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as polygonId from "./polygon-id";
export type { polygonId };
export type { DigiGoWallet } from "./DigiGoWallet";
export type { DigiGoWalletDeployer } from "./DigiGoWalletDeployer";
export type { MockPayment } from "./MockPayment";
